# Generated by Django 5.0.4 on 2024-05-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_scan',
            field=models.FileField(blank=True, upload_to='scans'),
        ),
    ]
